import {
  MdAccountCircle,
  MdAdd,
  MdArrowBack,
  MdArrowForward,
  MdAssessment,
  MdAssistant,
  MdBackup,
  MdCancel,
  MdChevronLeft,
  MdCreditCard,
  MdDashboard,
  MdDelete,
  MdDonutSmall,
  MdDriveFileRenameOutline,
  MdEqualizer,
  MdGridView,
  MdHome,
  MdInfo,
  MdInsertDriveFile,
  MdList,
  MdLocationCity,
  MdLogout,
  MdMap,
  MdMenu,
  MdMoreHoriz,
  MdMoreVert,
  MdNotifications,
  MdOpenInNew,
  MdPlace,
  MdRemove,
  MdRestore,
  MdSearch,
  MdSend,
  MdSettings,
} from "react-icons/md";

import { IoLayersSharp } from "react-icons/io5";

import { TbLayoutSidebarRight, TbPolygon } from "react-icons/tb";

import { FaRegEye, FaRegEyeSlash } from "react-icons/fa";

import { FcGoogle } from "react-icons/fc";

export type { IconType } from "react-icons";

export const Icons = {
  Account: MdAccountCircle,
  Add: MdAdd,
  ArrowLeft: MdArrowBack,
  ArrowRight: MdArrowForward,
  Assessment: MdAssessment,
  Assistant: MdAssistant,
  Backup: MdBackup,
  Building: MdLocationCity,
  Cancel: MdCancel,
  ChevronLeft: MdChevronLeft,
  CreditCard: MdCreditCard,
  Dashboard: MdDashboard,
  Delete: MdDelete,
  Equalizer: MdEqualizer,
  Eye: FaRegEye,
  EyeSlash: FaRegEyeSlash,
  Google: FcGoogle,
  Grid: MdGridView,
  Home: MdHome,
  Info: MdInfo,
  File: MdInsertDriveFile,
  Layers: IoLayersSharp,
  List: MdList,
  Logo: MdDonutSmall,
  LogOut: MdLogout,
  Map: MdMap,
  Menu: MdMenu,
  MoreHorizontal: MdMoreHoriz,
  MoreVertical: MdMoreVert,
  Notifications: MdNotifications,
  OpenInNew: MdOpenInNew,
  Place: MdPlace,
  Polygon: TbPolygon,
  Rename: MdDriveFileRenameOutline,
  Remove: MdRemove,
  Search: MdSearch,
  Send: MdSend,
  Settings: MdSettings,
  Sidebar: TbLayoutSidebarRight,
  Restore: MdRestore,
};
